[build]
  base    = "evohome-rebuild/packages/frontend"
  command = "npm install --legacy-peer-deps && npm run build"
  publish = ".next"

[functions]
  node_bundler = "esbuild"

[[plugins]]
  package = "@netlify/plugin-nextjs"
